### ISSUE TITLE
I get an error message KeyError: "sequence '10' not present"

### ISSUE THREAD

**Issue by kojix2** [friend1ws/nanomonsv#1]
Hello. 

I'm new to bioinformatics, but it's very interesting software.

I build the Dockerfile to try to run nanomonsv. 
When I ran the Quickstart commands in the README I got the following error. 
I'm not so familiar with Python. 

```
nanomonsv get output/test_tumor tests/resource/bam/test_tumor.bam GRCh38.d1.vd1.fa --control_prefix output/test_ctrl --control_bam tests/resource/bam/test_ctrl.bam
```

```
Traceback (most recent call last):
  File "/usr/local/bin/nanomonsv", line 33, in <module>
    sys.exit(load_entry_point('nanomonsv==0.1.0', 'console_scripts', 'nanomonsv')())
  File "/usr/local/lib/python3.6/dist-packages/nanomonsv/__init__.py", line 9, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/nanomonsv/run.py", line 111, in get_main
    args.tumor_prefix + ".refined_bp.txt", args.tumor_bam, args.reference_fasta, args.debug)
  File "/usr/local/lib/python3.6/dist-packages/nanomonsv/identify.py", line 219, in identify
    bret = get_refined_bp(tconsensus, fasta_file_ins, chr1, start1, end1, dir1, chr2, start2, end2, dir2, mode, hout_log)
  File "/usr/local/lib/python3.6/dist-packages/nanomonsv/identify.py", line 62, in get_refined_bp
    region1_seq = fasta_file_ins.fetch(chr1, bstart1 - 1, bend1)
  File "pysam/libcfaidx.pyx", line 303, in pysam.libcfaidx.FastaFile.fetch
KeyError: "sequence '10' not present"
```

What should I do?

**Comment by friend1ws** [comment]
Hi, Thank you very much for your interest in our software.
It seems there were problems in our previous test data, and now we updated the test data.
So I'm happy if you could try it once again.
Thank you!

**Comment by kojix2** [comment]
I ran it again.
I have confirmed that it works.
Thank you for the quick fix!
