### ISSUE TITLE
BAM format error & TypeError

### ISSUE THREAD

**Issue by nmc-ei** [friend1ws/nanomonsv#11]
Hi, thanks for developing this program.
I have two questions.

First,
I tried "nanomonsv parse" for test data (DRR258590).

```
$ wget https://sra-download.ncbi.nlm.nih.gov/traces/dra4/DRR/000252/DRR258590
$ sam-dump ./DRR258590.sra --output-file DRR258590.sam
$ samtools view -bS DRR258590.sam > DRR258590.bam
$ samtools sort ./DRR258590.bam -o ./DRR258590.sort
$ samtools index DRR258590.sort.bam
$ nanomonsv parse ./DRR258590.sort.bam output/test_ctrl
02/18/2021 17:35:34 - nanomonsv.utils - ERROR - BAM format error: ./DRR258590.sort.bam
```

Second,
I tried "nanomonsv parse" for our data.

`$ nanomonsv parse ./sample.sorted.bam output/test_tumor`

This run finished without error messages, then some files were outputed: ./output/test_tumor*.
Next, I tried "nanomonsv get" without control.

```
$ nanomonsv get output/test_tumor ./jurkat2nd.sorted.bam GRCh38.d1.vd1.fa
02/18/2021 16:22:06 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
02/18/2021 16:22:06 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
02/18/2021 16:22:06 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
02/18/2021 16:22:06 - nanomonsv.run - INFO - Gathering sequences of supporting reads
02/18/2021 16:22:07 - nanomonsv.run - INFO - Generate consensus sequences
Traceback (most recent call last):
  File "/home/hoge/anaconda3/envs/nanomon/bin/nanomonsv", line 8, in <module>
    sys.exit(main())
  File "/home/hoge/anaconda3/envs/nanomon/lib/python3.7/site-packages/nanomonsv/__init__.py", line 9, in main
    args.func(args)
  File "/home/hoge/anaconda3/envs/nanomon/lib/python3.7/site-packages/nanomonsv/run.py", line 184, in get_main
    args.use_racon, args.debug)
  File "/home/hoge/anaconda3/envs/nanomon/lib/python3.7/site-packages/nanomonsv/generate_consensus.py", line 205, in generate_consensus
    consensus_generator.print_consensus()
  File "/home/hoge/anaconda3/envs/nanomon/lib/python3.7/site-packages/nanomonsv/generate_consensus.py", line 185, in print_consensus
    self.print_consensus_mafft()
  File "/home/hoge/anaconda3/envs/nanomon/lib/python3.7/site-packages/nanomonsv/generate_consensus.py", line 86, in print_consensus_mafft
    hout_m = open(self.tmp_dir + '/' + self.temp_key + ".mafft_result.fa", 'w')
TypeError: can only concatenate str (not "NoneType") to str
```

Thank you.

CentOS Linux release 7.8.2003
Python 3.7.0
nanomonsv 0.3.0

**Comment by friend1ws** [comment]
Thank you for the interest in our software. Our software can accept BAM files generated by minimap2. So please use fastq-dump command in sra-tools and align them using minimap2.

**Comment by nmc-ei** [comment]
Thank you for your answer.

I aligned our data using minimap2.
"nanomonsv parse" looked successful, but "nanomonsv get" returned Error.

$ nanomonsv get output/test_tumor ./jurkat2nd.sort.bam GRCh38.d1.vd1.fa
02/24/2021 16:41:04 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
02/24/2021 16:41:06 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
02/24/2021 16:41:07 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
02/24/2021 16:41:09 - nanomonsv.run - INFO - Gathering sequences of supporting reads
02/24/2021 16:42:20 - nanomonsv.run - INFO - Generate consensus sequences
02/24/2021 16:45:24 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs
Traceback (most recent call last):
  File "/home/hoge/anaconda3/envs/nanomon/bin/nanomonsv", line 8, in <module>
    sys.exit(main())
  File "/home/hoge/anaconda3/envs/nanomon/lib/python3.7/site-packages/nanomonsv/__init__.py", line 9, in main
    args.func(args)
  File "/home/hoge/anaconda3/envs/nanomon/lib/python3.7/site-packages/nanomonsv/run.py", line 189, in get_main
    args.reference_fasta, args.debug)
  File "/home/hoge/anaconda3/envs/nanomon/lib/python3.7/site-packages/nanomonsv/locate_bp.py", line 87, in locate_bp
    bret = get_refined_bp(tconsensus, fasta_file_ins, chr1, start1, end1, dir1, chr2, start2, end2, dir2, mode, hout_log)
  File "/home/hoge/anaconda3/envs/nanomon/lib/python3.7/site-packages/nanomonsv/locate_bp.py", line 55, in get_refined_bp
    region_seq = fasta_file_ins.fetch(chr1, max(0, start1 - 100), end2 + 100)
  File "pysam/libcfaidx.pyx", line 303, in pysam.libcfaidx.FastaFile.fetch
KeyError: "sequence '1' not present"

**Comment by friend1ws** [comment]
Did you perfromed minimamp2 to GRCh38.d1.vd1.fa?
Could you send the result of the following command?
```
samtools view -H | head -n 30
```
I felt that there might be a possibility that the reference genome used in the alignment and nanomonsv is not consistent...

**Comment by nmc-ei** [comment]
Sorry, I misunderstood that it is compatible if they are GHR37.
I was able to get the result files by changing the reference file for "nanomonsv get".
Thank you.

**Comment by friend1ws** [comment]
Great!
