### ISSUE TITLE
Signal 6 (SIGABRT) when running get

### ISSUE THREAD

**Issue by asherbryant** [friend1ws/nanomonsv#39]
Hello -
We are analyzing deeply sequenced COLO829. After running parse, we ran get using the following script:
```
# bam files
TUMOR_BAM=/data/Lab/a_collab_COLO829/COLO829_cell_line_ONT_2021/nano_haplotagged_bams_grch38/colo829_tumor_xy.haplotagged.bam
NORMAL_BAM=/data/Lab/a_collab_COLO829/COLO829_cell_line_ONT_2021/nano_haplotagged_bams_grch38/colo829_normal_xy.haplotagged.bam


# reference files
HG=/data/Lab/references/grch38_chr.fasta


# parameters
THREADS=16
SIZE=30
DIRECTORY=/data/Lab/a_30bp


# source conda init file
source myconda
 

mamba activate nanomonsv

nanomonsv get /data/Lab/a_30bp/nanomonsv/nanomonsv_tumor $TUMOR_BAM \
$HG \
--control_prefix /data/Lab/a_30bp/nanomonsv/nanomonsv_normal --control_bam $NORMAL_BAM \
--use_racon \
--single_bnd \
--threads $THREADS
 
```
And this is the log from the job:
```
06/08/2023 23:39:15 - nanomonsv.run - INFO - Clustering rearrangement type supporting reads for putative SVs
06/08/2023 23:39:36 - nanomonsv.run - INFO - Clustering insertion type supporting reads for putative SVs
06/09/2023 01:40:21 - nanomonsv.run - INFO - Clustering deletion type supporting reads for putative SVs
06/09/2023 02:19:28 - nanomonsv.run - INFO - Clustering single breakend type supporting reads for putative SVs
06/09/2023 02:20:18 - nanomonsv.run - INFO - Gathering sequences of supporting reads
06/09/2023 03:32:46 - nanomonsv.run - INFO - Preparation for parallel execution
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (0)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (1)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (2)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (3)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (4)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (5)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (6)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (7)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (8)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (9)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (10)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (11)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (12)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (13)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (14)
06/09/2023 03:32:49 - nanomonsv.run - INFO - Generate consensus sequences (15)
06/09/2023 03:49:21 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (6)
06/09/2023 03:50:03 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (11)
06/09/2023 03:50:28 - nanomonsv.generate_consensus - WARNING - Command '['racon', '-u', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.15.txt.tmp_dir/chr4,184954778,184954798,+,chr4,184954779,184954799,-,i,7785.supporting_read.fa', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.15.txt.tmp_dir/chr4,184954778,184954798,+,chr4,184954779,184954799,-,i,7785.parasail.paf', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.15.txt.tmp_dir/chr4,184954778,184954798,+,chr4,184954779,184954799,-,i,7785.tmp.seg.first.fa']' returned non-zero exit status 1.
06/09/2023 03:55:16 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (12)
06/09/2023 03:57:26 - nanomonsv.run - INFO - End Process (0): ret_code=1
06/09/2023 03:59:18 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (7)
06/09/2023 04:00:46 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (1)
06/09/2023 04:01:35 - nanomonsv.generate_consensus - WARNING - Command '['racon', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.sbnd.10.txt.tmp_dir/chr13,58739005,58739046,-,b,340.supporting_read.fa', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.sbnd.10.txt.tmp_dir/chr13,58739005,58739046,-,b,340_ova_minimap2.paf', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.sbnd.10.txt.tmp_dir/chr13,58739005,58739046,-,b,340_ref.fa']' returned non-zero exit status 1.
06/09/2023 04:04:19 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (10)
06/09/2023 04:04:20 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (5)
06/09/2023 04:20:06 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (15)
06/09/2023 04:36:18 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (13)
06/09/2023 04:58:01 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (2)
06/09/2023 05:54:30 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (3)
06/09/2023 06:00:40 - nanomonsv.generate_consensus - WARNING - Command '['racon', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.sbnd.9.txt.tmp_dir/chr4,91998940,91999027,-,b,1160.supporting_read.fa', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.sbnd.9.txt.tmp_dir/chr4,91998940,91999027,-,b,1160_ova_minimap2.paf', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.sbnd.9.txt.tmp_dir/chr4,91998940,91999027,-,b,1160_ref.fa']' returned non-zero exit status 1.
06/09/2023 06:04:02 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (9)
06/09/2023 06:19:46 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (14)
06/09/2023 06:52:13 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (4)
06/09/2023 08:25:59 - nanomonsv.run - INFO - Locating single-base resolution break points for candidate SVs (8)
06/09/2023 14:03:53 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (6)
06/09/2023 15:08:28 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (11)
06/09/2023 15:12:14 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (7)
06/09/2023 15:17:41 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (5)
06/09/2023 15:34:20 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (1)
06/09/2023 15:41:05 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (12)
06/09/2023 15:46:35 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (10)
06/09/2023 15:50:17 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (15)
06/09/2023 15:54:22 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (13)
06/09/2023 16:19:33 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (2)
06/09/2023 16:56:14 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (9)
06/09/2023 16:58:09 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (14)
06/09/2023 16:59:39 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (3)
06/09/2023 17:06:00 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (4)
06/09/2023 17:12:22 - nanomonsv.run - INFO - Counting the number of supporting read for the tumor by realignment of SV candidate segments (8)
06/10/2023 12:34:12 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (1)
06/10/2023 12:53:47 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (15)
06/10/2023 13:04:59 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (7)
06/10/2023 13:05:09 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (3)
06/10/2023 13:14:31 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (12)
06/10/2023 13:24:32 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (13)
06/10/2023 13:35:09 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (6)
06/10/2023 13:35:26 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (2)
06/10/2023 13:41:09 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (5)
06/10/2023 13:41:40 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (9)
06/10/2023 13:43:26 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (14)
06/10/2023 13:43:39 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (4)
06/10/2023 13:43:49 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (8)
06/10/2023 13:47:09 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (11)
06/10/2023 13:49:04 - nanomonsv.run - INFO - Counting the number of supporting read for the control by realignment of SV candidate segments (10)
06/11/2023 06:48:50 - nanomonsv.run - INFO - End Process (1): ret_code=0
06/11/2023 07:45:37 - nanomonsv.run - INFO - End Process (15): ret_code=0
06/11/2023 08:10:44 - nanomonsv.run - INFO - End Process (7): ret_code=0
06/11/2023 08:12:59 - nanomonsv.run - INFO - End Process (3): ret_code=0
06/11/2023 08:40:36 - nanomonsv.run - INFO - End Process (12): ret_code=0
06/11/2023 08:51:25 - nanomonsv.run - INFO - End Process (13): ret_code=0
06/11/2023 09:13:45 - nanomonsv.run - INFO - End Process (2): ret_code=0
06/11/2023 09:14:53 - nanomonsv.run - INFO - End Process (6): ret_code=0
06/11/2023 09:31:33 - nanomonsv.run - INFO - End Process (4): ret_code=0
06/11/2023 09:39:20 - nanomonsv.run - INFO - End Process (5): ret_code=0
06/11/2023 09:41:36 - nanomonsv.run - INFO - End Process (8): ret_code=0
06/11/2023 09:42:03 - nanomonsv.run - INFO - End Process (9): ret_code=0
06/11/2023 09:43:00 - nanomonsv.run - INFO - End Process (14): ret_code=0
06/11/2023 09:44:33 - nanomonsv.run - INFO - End Process (11): ret_code=0
06/11/2023 09:48:12 - nanomonsv.run - INFO - End Process (10): ret_code=0
Traceback (most recent call last):
  File "/gpfs/gsfs8/users/ba/conda/envs/nanomonsv/bin/nanomonsv", line 10, in <module>
    sys.exit(main())
  File "/gpfs/gsfs8/users/ba/conda/envs/nanomonsv/lib/python3.10/site-packages/nanomonsv/__init__.py", line 13, in main
    args.func(args)
  File "/gpfs/gsfs8/users/ba/conda/envs/nanomonsv/lib/python3.10/site-packages/nanomonsv/run.py", line 352, in get_main
    raise Exception(err_message)
Exception: Command '['minimap2', '-x', 'ava-ont', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.sbnd.0.txt.tmp_dir/chr3,25290068,25290116,-,b,997.supporting_read.fa', '/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.sbnd.0.txt.tmp_dir/chr3,25290068,25290116,-,b,997.supporting_read.fa']' died with <Signals.SIGABRT: 6>.
```
Any help would be much appreciated!

**Comment by friend1ws** [comment]
Thanks for your interest in nanomonsv.
What is the amount of memory?

**Comment by asherbryant** [comment]
200 g were allocated but required was far below that.
![image](https://github.com/friend1ws/nanomonsv/assets/101344943/561b223f-d043-40ad-9484-777aaad9459f)

**Comment by friend1ws** [comment]
I saw this kind of bug for the first time.
If it is OK on your side, could you share the following files?

```
/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.sbnd.0.txt.tmp_dir/chr3,25290068,25290116,-,b,997.supporting_read.fa
/data/Lab/a_30bp/nanomonsv/nanomonsv_tumor.consensus_seq.sbnd.0.txt.tmp_dir/chr3,25290068,25290116,-,b,997.supporting_read.fa
```

Also, I just released a new version of nanomonsv (v0.6.0), which significantly reduced SV candidates (as well as single breakend SVs). So you may succeed when using the new version.

**Comment by asherbryant** [comment]
I don't see a `nanomonsv_tumor.consensus_seq.sbnd.0.txt.tmp_dir` directory or `chr3,25290068,25290116,-,b,997.supporting_read.fa` file. This is whats in `/data/Lab/a_30bp/nanomonsv`: 
```
nanomonsv_normal.bp_info.sorted.bed.gz                       nanomonsv_tumor.realignment.tumor.sread_count.6.txt
nanomonsv_normal.bp_info.sorted.bed.gz.tbi                   nanomonsv_tumor.realignment.tumor.sread_count.7.txt
nanomonsv_normal.deletion.sorted.bed.gz                      nanomonsv_tumor.realignment.tumor.sread_count.8.txt
nanomonsv_normal.deletion.sorted.bed.gz.tbi                  nanomonsv_tumor.realignment.tumor.sread_count.9.txt
nanomonsv_normal.insertion.sorted.bed.gz                     nanomonsv_tumor.realignment.tumor.sread_count.sbnd.10.txt
nanomonsv_normal.insertion.sorted.bed.gz.tbi                 nanomonsv_tumor.realignment.tumor.sread_count.sbnd.11.txt
nanomonsv_normal.rearrangement.sorted.bedpe.gz               nanomonsv_tumor.realignment.tumor.sread_count.sbnd.12.txt
nanomonsv_normal.rearrangement.sorted.bedpe.gz.tbi           nanomonsv_tumor.realignment.tumor.sread_count.sbnd.13.txt
nanomonsv_tumor.bp_info.sorted.bed.gz                        nanomonsv_tumor.realignment.tumor.sread_count.sbnd.14.txt
nanomonsv_tumor.bp_info.sorted.bed.gz.tbi                    nanomonsv_tumor.realignment.tumor.sread_count.sbnd.15.txt
nanomonsv_tumor.consensus_seq.0.txt                          nanomonsv_tumor.realignment.tumor.sread_count.sbnd.1.txt
nanomonsv_tumor.consensus_seq.10.txt                         nanomonsv_tumor.realignment.tumor.sread_count.sbnd.2.txt
nanomonsv_tumor.consensus_seq.11.txt                         nanomonsv_tumor.realignment.tumor.sread_count.sbnd.3.txt
nanomonsv_tumor.consensus_seq.12.txt                         nanomonsv_tumor.realignment.tumor.sread_count.sbnd.4.txt
nanomonsv_tumor.consensus_seq.13.txt                         nanomonsv_tumor.realignment.tumor.sread_count.sbnd.5.txt
nanomonsv_tumor.consensus_seq.14.txt                         nanomonsv_tumor.realignment.tumor.sread_count.sbnd.6.txt
nanomonsv_tumor.consensus_seq.15.txt                         nanomonsv_tumor.realignment.tumor.sread_count.sbnd.7.txt
nanomonsv_tumor.consensus_seq.1.txt                          nanomonsv_tumor.realignment.tumor.sread_count.sbnd.8.txt
nanomonsv_tumor.consensus_seq.2.txt                          nanomonsv_tumor.realignment.tumor.sread_count.sbnd.9.txt
nanomonsv_tumor.consensus_seq.3.txt                          nanomonsv_tumor.realignment.tumor.sread_info.10.txt
nanomonsv_tumor.consensus_seq.4.txt                          nanomonsv_tumor.realignment.tumor.sread_info.11.txt
nanomonsv_tumor.consensus_seq.5.txt                          nanomonsv_tumor.realignment.tumor.sread_info.12.txt
nanomonsv_tumor.consensus_seq.6.txt                          nanomonsv_tumor.realignment.tumor.sread_info.13.txt
nanomonsv_tumor.consensus_seq.7.txt                          nanomonsv_tumor.realignment.tumor.sread_info.14.txt
nanomonsv_tumor.consensus_seq.8.txt                          nanomonsv_tumor.realignment.tumor.sread_info.15.txt
nanomonsv_tumor.consensus_seq.9.txt                          nanomonsv_tumor.realignment.tumor.sread_info.1.txt
nanomonsv_tumor.consensus_seq.sbnd.0.txt                     nanomonsv_tumor.realignment.tumor.sread_info.2.txt
nanomonsv_tumor.consensus_seq.sbnd.10.txt                    nanomonsv_tumor.realignment.tumor.sread_info.3.txt
nanomonsv_tumor.consensus_seq.sbnd.11.txt                    nanomonsv_tumor.realignment.tumor.sread_info.4.txt
nanomonsv_tumor.consensus_seq.sbnd.12.txt                    nanomonsv_tumor.realignment.tumor.sread_info.5.txt
nanomonsv_tumor.consensus_seq.sbnd.13.txt                    nanomonsv_tumor.realignment.tumor.sread_info.6.txt
nanomonsv_tumor.consensus_seq.sbnd.14.txt                    nanomonsv_tumor.realignment.tumor.sread_info.7.txt
nanomonsv_tumor.consensus_seq.sbnd.15.txt                    nanomonsv_tumor.realignment.tumor.sread_info.8.txt
nanomonsv_tumor.consensus_seq.sbnd.1.txt                     nanomonsv_tumor.realignment.tumor.sread_info.9.txt
nanomonsv_tumor.consensus_seq.sbnd.2.txt                     nanomonsv_tumor.realignment.tumor.sread_info.sbnd.10.txt
nanomonsv_tumor.consensus_seq.sbnd.3.txt                     nanomonsv_tumor.realignment.tumor.sread_info.sbnd.11.txt
nanomonsv_tumor.consensus_seq.sbnd.4.txt                     nanomonsv_tumor.realignment.tumor.sread_info.sbnd.12.txt
nanomonsv_tumor.consensus_seq.sbnd.5.txt                     nanomonsv_tumor.realignment.tumor.sread_info.sbnd.13.txt
nanomonsv_tumor.consensus_seq.sbnd.6.txt                     nanomonsv_tumor.realignment.tumor.sread_info.sbnd.14.txt
nanomonsv_tumor.consensus_seq.sbnd.7.txt                     nanomonsv_tumor.realignment.tumor.sread_info.sbnd.15.txt
nanomonsv_tumor.consensus_seq.sbnd.8.txt                     nanomonsv_tumor.realignment.tumor.sread_info.sbnd.1.txt
nanomonsv_tumor.consensus_seq.sbnd.9.txt                     nanomonsv_tumor.realignment.tumor.sread_info.sbnd.2.txt
nanomonsv_tumor.deletion.sorted.bed.gz                       nanomonsv_tumor.realignment.tumor.sread_info.sbnd.3.txt
nanomonsv_tumor.deletion.sorted.bed.gz.tbi                   nanomonsv_tumor.realignment.tumor.sread_info.sbnd.4.txt
nanomonsv_tumor.deletion.sorted.clustered.bedpe              nanomonsv_tumor.realignment.tumor.sread_info.sbnd.5.txt
nanomonsv_tumor.insertion.sorted.bed.gz                      nanomonsv_tumor.realignment.tumor.sread_info.sbnd.6.txt
nanomonsv_tumor.insertion.sorted.bed.gz.tbi                  nanomonsv_tumor.realignment.tumor.sread_info.sbnd.7.txt
nanomonsv_tumor.insertion.sorted.clustered.bedpe             nanomonsv_tumor.realignment.tumor.sread_info.sbnd.8.txt
nanomonsv_tumor.realignment.control.sread_count.10.txt       nanomonsv_tumor.realignment.tumor.sread_info.sbnd.9.txt
nanomonsv_tumor.realignment.control.sread_count.11.txt       nanomonsv_tumor.rearrangement.sorted.bedpe.gz
nanomonsv_tumor.realignment.control.sread_count.12.txt       nanomonsv_tumor.rearrangement.sorted.bedpe.gz.tbi
nanomonsv_tumor.realignment.control.sread_count.13.txt       nanomonsv_tumor.rearrangement.sorted.clustered.bedpe
nanomonsv_tumor.realignment.control.sread_count.14.txt       nanomonsv_tumor.refined_bp.0.txt
nanomonsv_tumor.realignment.control.sread_count.15.txt       nanomonsv_tumor.refined_bp.10.txt
nanomonsv_tumor.realignment.control.sread_count.1.txt        nanomonsv_tumor.refined_bp.11.txt
nanomonsv_tumor.realignment.control.sread_count.2.txt        nanomonsv_tumor.refined_bp.12.txt
nanomonsv_tumor.realignment.control.sread_count.3.txt        nanomonsv_tumor.refined_bp.13.txt
nanomonsv_tumor.realignment.control.sread_count.4.txt        nanomonsv_tumor.refined_bp.14.txt
nanomonsv_tumor.realignment.control.sread_count.5.txt        nanomonsv_tumor.refined_bp.15.txt
nanomonsv_tumor.realignment.control.sread_count.6.txt        nanomonsv_tumor.refined_bp.1.txt
nanomonsv_tumor.realignment.control.sread_count.7.txt        nanomonsv_tumor.refined_bp.2.txt
nanomonsv_tumor.realignment.control.sread_count.8.txt        nanomonsv_tumor.refined_bp.3.txt
nanomonsv_tumor.realignment.control.sread_count.9.txt        nanomonsv_tumor.refined_bp.4.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.10.txt  nanomonsv_tumor.refined_bp.5.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.11.txt  nanomonsv_tumor.refined_bp.6.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.12.txt  nanomonsv_tumor.refined_bp.7.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.13.txt  nanomonsv_tumor.refined_bp.8.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.14.txt  nanomonsv_tumor.refined_bp.9.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.15.txt  nanomonsv_tumor.refined_bp.sbnd.0.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.1.txt   nanomonsv_tumor.refined_bp.sbnd.10.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.2.txt   nanomonsv_tumor.refined_bp.sbnd.11.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.3.txt   nanomonsv_tumor.refined_bp.sbnd.12.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.4.txt   nanomonsv_tumor.refined_bp.sbnd.13.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.5.txt   nanomonsv_tumor.refined_bp.sbnd.14.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.6.txt   nanomonsv_tumor.refined_bp.sbnd.15.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.7.txt   nanomonsv_tumor.refined_bp.sbnd.1.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.8.txt   nanomonsv_tumor.refined_bp.sbnd.2.txt
nanomonsv_tumor.realignment.control.sread_count.sbnd.9.txt   nanomonsv_tumor.refined_bp.sbnd.3.txt
nanomonsv_tumor.realignment.control.sread_info.10.txt        nanomonsv_tumor.refined_bp.sbnd.4.txt
nanomonsv_tumor.realignment.control.sread_info.11.txt        nanomonsv_tumor.refined_bp.sbnd.5.txt
nanomonsv_tumor.realignment.control.sread_info.12.txt        nanomonsv_tumor.refined_bp.sbnd.6.txt
nanomonsv_tumor.realignment.control.sread_info.13.txt        nanomonsv_tumor.refined_bp.sbnd.7.txt
nanomonsv_tumor.realignment.control.sread_info.14.txt        nanomonsv_tumor.refined_bp.sbnd.8.txt
nanomonsv_tumor.realignment.control.sread_info.15.txt        nanomonsv_tumor.refined_bp.sbnd.9.txt
nanomonsv_tumor.realignment.control.sread_info.1.txt         nanomonsv_tumor.singlebreakend.sorted.clustered.bed
nanomonsv_tumor.realignment.control.sread_info.2.txt         nanomonsv_tumor.support_read_seq.0.txt
nanomonsv_tumor.realignment.control.sread_info.3.txt         nanomonsv_tumor.support_read_seq.10.txt
nanomonsv_tumor.realignment.control.sread_info.4.txt         nanomonsv_tumor.support_read_seq.11.txt
nanomonsv_tumor.realignment.control.sread_info.5.txt         nanomonsv_tumor.support_read_seq.12.txt
nanomonsv_tumor.realignment.control.sread_info.6.txt         nanomonsv_tumor.support_read_seq.13.txt
nanomonsv_tumor.realignment.control.sread_info.7.txt         nanomonsv_tumor.support_read_seq.14.txt
nanomonsv_tumor.realignment.control.sread_info.8.txt         nanomonsv_tumor.support_read_seq.15.txt
nanomonsv_tumor.realignment.control.sread_info.9.txt         nanomonsv_tumor.support_read_seq.1.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.10.txt   nanomonsv_tumor.support_read_seq.2.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.11.txt   nanomonsv_tumor.support_read_seq.3.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.12.txt   nanomonsv_tumor.support_read_seq.4.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.13.txt   nanomonsv_tumor.support_read_seq.5.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.14.txt   nanomonsv_tumor.support_read_seq.6.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.15.txt   nanomonsv_tumor.support_read_seq.7.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.1.txt    nanomonsv_tumor.support_read_seq.8.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.2.txt    nanomonsv_tumor.support_read_seq.9.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.3.txt    nanomonsv_tumor.support_read_seq.sbnd.0.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.4.txt    nanomonsv_tumor.support_read_seq.sbnd.10.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.5.txt    nanomonsv_tumor.support_read_seq.sbnd.11.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.6.txt    nanomonsv_tumor.support_read_seq.sbnd.12.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.7.txt    nanomonsv_tumor.support_read_seq.sbnd.13.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.8.txt    nanomonsv_tumor.support_read_seq.sbnd.14.txt
nanomonsv_tumor.realignment.control.sread_info.sbnd.9.txt    nanomonsv_tumor.support_read_seq.sbnd.15.txt
nanomonsv_tumor.realignment.tumor.sread_count.10.txt         nanomonsv_tumor.support_read_seq.sbnd.1.txt
nanomonsv_tumor.realignment.tumor.sread_count.11.txt         nanomonsv_tumor.support_read_seq.sbnd.2.txt
nanomonsv_tumor.realignment.tumor.sread_count.12.txt         nanomonsv_tumor.support_read_seq.sbnd.3.txt
nanomonsv_tumor.realignment.tumor.sread_count.13.txt         nanomonsv_tumor.support_read_seq.sbnd.4.txt
nanomonsv_tumor.realignment.tumor.sread_count.14.txt         nanomonsv_tumor.support_read_seq.sbnd.5.txt
nanomonsv_tumor.realignment.tumor.sread_count.15.txt         nanomonsv_tumor.support_read_seq.sbnd.6.txt
nanomonsv_tumor.realignment.tumor.sread_count.1.txt          nanomonsv_tumor.support_read_seq.sbnd.7.txt
nanomonsv_tumor.realignment.tumor.sread_count.2.txt          nanomonsv_tumor.support_read_seq.sbnd.8.txt
nanomonsv_tumor.realignment.tumor.sread_count.3.txt          nanomonsv_tumor.support_read_seq.sbnd.9.txt
nanomonsv_tumor.realignment.tumor.sread_count.4.txt          nanomonsv_tumor.support_read_seq.sbnd.txt
nanomonsv_tumor.realignment.tumor.sread_count.5.txt          nanomonsv_tumor.support_read_seq.txt




```

**Comment by fenderglass** [comment]
@friend1ws thanks for helping here! It seems that your 0.6.0 release is ready to get updated in bioconda as well, pending a review: https://github.com/bioconda/bioconda-recipes/pull/41495. Do you want me to help with that?

**Comment by friend1ws** [comment]
@fenderglass Thank you for your interest in nanomonsv! Yes, I'm happy if you could review of the 0.6.0 release.

**Comment by fenderglass** [comment]
Done! 0.6.0 should be installable with bioconda in a couple hours.

**Comment by friend1ws** [comment]
@fenderglass Thanks!

@asherbryant Please try with v0.6.0. Just in case, I appreciate it if you could add "--debug" option which will keep all the intermediate files so that you could send the problematic files when similar types of errors happen.

**Comment by friend1ws** [comment]
@asherbryant I have encountered the same problem when evaluating HiFi sequence data. In fact, we are now setting the memory limit in minimap2 for 1Gb, and when I changed it by `--max_memory_minimap2 8`, I could run successfully. So please try `--max_memory_minimap2 8` or `--max_memory_minimap2 12`, in the nanomonsv get function.

I do not think this is an elegant implementation, and I will try to fix it soon.

**Comment by asherbryant** [comment]
Thank you! I will try that.
