### ISSUE TITLE
 local variable 'is_insert_type' referenced before assignment

### ISSUE THREAD

**Issue by charliechen912ilovbash** [friend1ws/nanomonsv#47]
I am using version 0.7.0, the filtering step, I run:
```
python3  /nanomonsv-0.7.0/nanomonsv/misc/post_filter_by_v0.3.py  tumor.nanomonsv.result.txt.sv_type  tumor.nanomonsv.result.txt.sv_type.filt   GDC-GRCh38_plus_AAV2-autosome-X.fa  --simple_repeat_bed  simpleRepeat.bed.gz
```

and it came out:

```
Traceback (most recent call last):
  File "/nanomonsv-0.7.0/nanomonsv/misc/post_filter_by_v0.3.py", line 312, in <module>
    post_filter_main(args)
  File "/nanomonsv-0.7.0/nanomonsv/misc/post_filter_by_v0.3.py", line 263, in post_filter_main
    if is_insert_type:
UnboundLocalError: local variable 'is_insert_type' referenced before assignment
```

**Comment by friend1ws** [comment]
Let's merge into simple repeat filtered result is not included in vcf output #48.
