### ISSUE TITLE
unrecognized arguments - fasta file

### ISSUE THREAD

**Issue by setshabaTaukobong** [friend1ws/nanomonsv#66]
Good day,
I am trying to run the nanomonsv insert_classify command as follows:

nanomonsv: error: unrecognized arguments: GRCh38_latest_genomic.fa

However I am getting the following error:
nanomonsv: error: unrecognized arguments: GRCh38_latest_genomic.fa

I am not sure why my fasta file is not being recognised. Could I please get some assistance on this. Thank you.

**Comment by friend1ws** [comment]
Thanks for using nanomonsv. Could you provide the exact command you used?

**Comment by setshabaTaukobong** [comment]
Hi there, thank you for getting back to me. 
The command:

nanomonsv insert_classify --grc False --genome_id hg38 --debug test_tumor.nanomonsv.result.txt output_file GRCh38_latest_genomic.fa

**Comment by setshabaTaukobong** [comment]
Hi there @friend1ws , I am still struggling with this issue and would appreciate some help. 
Thank you

**Comment by friend1ws** [comment]
Hi, could you try removing `--grc False `?

**Comment by setshabaTaukobong** [comment]
Hi @friend1ws I have tried using --grc False but I still get the same error (please see previous text with command).

**Comment by friend1ws** [comment]
Could you try the following command?
```
nanomonsv insert_classify --genome_id hg38 --debug test_tumor.nanomonsv.result.txt output_file GRCh38_latest_genomic.fa
```

**Comment by setshabaTaukobong** [comment]
@friend1ws  
So I tried that and I get the following error:

Traceback (most recent call last):
  File "/apps/chpc/bio/anaconda3-2020.02/envs/nanomonsv/bin/nanomonsv", line 10, in <module>
    sys.exit(main())
  File "/apps/chpc/bio/anaconda3-2020.02/envs/nanomonsv/lib/python3.10/site-packages/nanomonsv/__init__.py", line 13, in main
    args.func(args)
  File "/apps/chpc/bio/anaconda3-2020.02/envs/nanomonsv/lib/python3.10/site-packages/nanomonsv/run.py", line 524, in insert_classify_main
    import annot_utils.exon
ModuleNotFoundError: No module named 'annot_utils'
(nanomonsv) [staukobong@cnode0986 output]$ nanomonsv insert_classify --genome_id hg38 --debug test_tumor.nanomonsv.result.txt output_file GRCh38_latest_genomic.fa
Traceback (most recent call last):
  File "/apps/chpc/bio/anaconda3-2020.02/envs/nanomonsv/bin/nanomonsv", line 10, in <module>
    sys.exit(main())
  File "/apps/chpc/bio/anaconda3-2020.02/envs/nanomonsv/lib/python3.10/site-packages/nanomonsv/__init__.py", line 13, in main
    args.func(args)
  File "/apps/chpc/bio/anaconda3-2020.02/envs/nanomonsv/lib/python3.10/site-packages/nanomonsv/run.py", line 524, in insert_classify_main
    import annot_utils.exon
ModuleNotFoundError: No module named 'annot_utils'

**Comment by friend1ws** [comment]
nanomonsv insert_classify currently needs annot_utils pacakge. So please install it.

**Comment by friend1ws** [comment]
For using insert_classify, currently we do not recommend using conda. I'm trying to reduce the necessary packages and softwares. But currently I would use venv.

```
python -m venv nanomonsv_v0.7.2
source nanomonsv_v0.7.2/source/bin/activate
pip install nanomonsv
pip install annot_utils
pip install (other packages).
```

**Comment by setshabaTaukobong** [comment]
will do. Thank you @friend1ws

**Comment by eesiribloom** [comment]
does the `insert_classify` command follow the same methodology as the classififcation of insertions in the [manuscript ] ?(https://academic.oup.com/nar/article/51/14/e74/7201946?login=true)
